### ISSUE TITLE
TypeError: Bonjour is not a constructor

### ISSUE THREAD

**Issue by EduardSat** [onlxltd/bonjour-service#64]
Hello! installed bonjour-service v. 1.2.1 for nodejs service

using as following:
```
import Bonjour from 'bonjour-service'
const instance = new Bonjour()
```

but getting TypeError: Bonjour is not a constructor

**Comment by Tonton-Blax** [comment]
Can confirm, tried with node 20.x and 22.x.

When importing `bonjour-service` in ES modules, using `import Bonjour from 'bonjour-service'` leads to the error `TypeError: Bonjour is not a constructor`. This seems to happen because of the `Bonjour` class being exported under the `default` property rather than directly as a default export.

**Workaround**:

Access `default` explicitly:

   ```javascript
   import BonjourModule from 'bonjour-service';
   const Bonjour = BonjourModule.default;
   ```

**Comment by mdidon** [comment]
Documentation is being update. Thanks
